"use client";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import type { Metadata } from "next";
import { Fira_Mono } from "next/font/google";
import { useState } from "react";

const fira = Fira_Mono({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [light, setLight] = useState<boolean>(false);
  return (
    <html lang="en" className={light ? "light" : "dark"}>
      <body className={`${fira.className} grid place-content-center`}>
        <button onClick={() => setLight(!light)}>Theme switch</button>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
